version: '3'
services:
  nginx:
    build:
      context: .
    stdin_open: true
    # Enables the -t option inn docker container
    tty: true
    restart: "always"
    volumes:
      - "/etc/nginx/sites-available:/etc/nginx/sites-available"
      - "/etc/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "/var/www/:/var/www"
      - "/var/log/nginx/:/var/log/nginx/"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
    network_mode: host
