version: '2'

services:
  nginx:
    build:
      context: .
      restart: always
      network_mode: host
      volumes:
        - /etc/nginx/sites-available:/etc/nginx/sites-available
        - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
        - /var/www/:/var/www
        - /var/log/nginx/:/var/log/nginx/
        - /etc/letsencrypt/:/etc/letsencrypt/