version: '3.4'
services:
  nginx:
    build:
      context: .
      restart: always
      volumes:
        - type: bind
          source: /etc/nginx/sites-available
          target: /etc/nginx/sites-available
        - type: bind
          source: /etc/nginx/sites-enabled
          target: /etc/nginx/sites-enabled
        - type: bind
          source: /var/www/
          target: /var/www
        - type: bind
          source: /var/log/nginx/
          target: /var/log/nginx/
        - type: bind
          source: /etc/letsencrypt/
          target: /etc/letsencrypt/
      network: host
