# Use postgres/example user/password credentials
version: '2.3'

services:

  pg:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: chang3m3
    ports:
       - 5432:5432

  admin:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@valle.us
        PGADMIN_DEFAULT_PASSWORD: chang3m3
    ports:
        - 5051:80
