version: '2.3'

services:
  bridge:
    build:
      context: .
    stdin_open: true
    # Enables the 
      restart: always
      stdin_open: true
      # Enables the -t option inn docker container
      tty: true
      volumes:
        - /opt/schedulr-bridge:/opt/schedulr-bridge
      network_mode: host